//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kosarica
    {
        public int nID { get; set; }
        public int pID { get; set; }
        public Nullable<decimal> proKolicina { get; set; }
        public Nullable<decimal> proIznos { get; set; }
    
        public virtual Narudzbe Narudzbe { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
