//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbe()
        {
            this.Kosaricas = new HashSet<Kosarica>();
        }
    
        public int nID { get; set; }
        public Nullable<int> kID { get; set; }
        public Nullable<int> popID { get; set; }
        public Nullable<decimal> nTotal { get; set; }
        public Nullable<System.DateTime> nVrijeme { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kosarica> Kosaricas { get; set; }
        public virtual Popusti Popusti { get; set; }
    }
}
